
FUNDS = [
    # ── US LARGE CAP EQUITY ──────────────────────────────────────────────────
    {"ticker": "SPY",  "name": "SPDR S&P 500 ETF Trust",                    "category": "US Large Cap"},
    {"ticker": "IVV",  "name": "iShares Core S&P 500 ETF",                  "category": "US Large Cap"},
    {"ticker": "VOO",  "name": "Vanguard S&P 500 ETF",                      "category": "US Large Cap"},
    {"ticker": "VTI",  "name": "Vanguard Total Stock Market ETF",            "category": "US Large Cap"},
    {"ticker": "ITOT", "name": "iShares Core S&P Total US Stock Market ETF", "category": "US Large Cap"},
    {"ticker": "SCHB", "name": "Schwab US Broad Market ETF",                 "category": "US Large Cap"},
    {"ticker": "IWB",  "name": "iShares Russell 1000 ETF",                  "category": "US Large Cap"},
    {"ticker": "RSP",  "name": "Invesco S&P 500 Equal Weight ETF",           "category": "US Large Cap"},
    {"ticker": "SPTM", "name": "SPDR Portfolio S&P 1500 Composite ETF",      "category": "US Large Cap"},
    {"ticker": "VTV",  "name": "Vanguard Value ETF",                         "category": "US Value"},
    {"ticker": "IWD",  "name": "iShares Russell 1000 Value ETF",             "category": "US Value"},
    {"ticker": "SPYV", "name": "SPDR Portfolio S&P 500 Value ETF",           "category": "US Value"},
    {"ticker": "VUG",  "name": "Vanguard Growth ETF",                        "category": "US Growth"},
    {"ticker": "IWF",  "name": "iShares Russell 1000 Growth ETF",            "category": "US Growth"},
    {"ticker": "SPYG", "name": "SPDR Portfolio S&P 500 Growth ETF",          "category": "US Growth"},
    {"ticker": "QQQ",  "name": "Invesco QQQ Trust (Nasdaq-100)",             "category": "US Growth"},
    {"ticker": "QQQM", "name": "Invesco Nasdaq-100 ETF",                     "category": "US Growth"},
    {"ticker": "SCHG", "name": "Schwab US Large-Cap Growth ETF",             "category": "US Growth"},
    {"ticker": "SCHD", "name": "Schwab US Dividend Equity ETF",              "category": "US Dividend"},
    {"ticker": "DVY",  "name": "iShares Select Dividend ETF",                "category": "US Dividend"},
    {"ticker": "SDY",  "name": "SPDR S&P Dividend ETF",                      "category": "US Dividend"},
    {"ticker": "HDV",  "name": "iShares Core High Dividend ETF",             "category": "US Dividend"},
    {"ticker": "VIG",  "name": "Vanguard Dividend Appreciation ETF",         "category": "US Dividend"},
    {"ticker": "VYM",  "name": "Vanguard High Dividend Yield ETF",           "category": "US Dividend"},
    {"ticker": "DGRO", "name": "iShares Core Dividend Growth ETF",           "category": "US Dividend"},
    {"ticker": "NOBL", "name": "ProShares S&P 500 Dividend Aristocrats ETF", "category": "US Dividend"},
    {"ticker": "RDVY", "name": "First Trust Rising Dividend Achievers ETF",  "category": "US Dividend"},

    # ── US FACTOR / SMART BETA ───────────────────────────────────────────────
    {"ticker": "QUAL", "name": "iShares MSCI USA Quality Factor ETF",        "category": "US Factor"},
    {"ticker": "MTUM", "name": "iShares MSCI USA Momentum Factor ETF",       "category": "US Factor"},
    {"ticker": "VLUE", "name": "iShares MSCI USA Value Factor ETF",          "category": "US Factor"},
    {"ticker": "USMV", "name": "iShares MSCI USA Min Vol Factor ETF",        "category": "US Factor"},
    {"ticker": "SPLV", "name": "Invesco S&P 500 Low Volatility ETF",         "category": "US Factor"},
    {"ticker": "SPHQ", "name": "Invesco S&P 500 Quality ETF",                "category": "US Factor"},
    {"ticker": "SIZE", "name": "iShares MSCI USA Size Factor ETF",           "category": "US Factor"},
    {"ticker": "LRGF", "name": "iShares US Equity Factor ETF",               "category": "US Factor"},

    # ── US MID CAP ───────────────────────────────────────────────────────────
    {"ticker": "MDY",  "name": "SPDR S&P MidCap 400 ETF",                   "category": "US Mid Cap"},
    {"ticker": "VO",   "name": "Vanguard Mid-Cap ETF",                       "category": "US Mid Cap"},
    {"ticker": "IJH",  "name": "iShares Core S&P Mid-Cap ETF",               "category": "US Mid Cap"},
    {"ticker": "IWR",  "name": "iShares Russell Mid-Cap ETF",                "category": "US Mid Cap"},
    {"ticker": "SCHM", "name": "Schwab US Mid-Cap ETF",                      "category": "US Mid Cap"},
    {"ticker": "VBK",  "name": "Vanguard Small-Cap Growth ETF",              "category": "US Mid Cap"},
    {"ticker": "VBR",  "name": "Vanguard Small-Cap Value ETF",               "category": "US Mid Cap"},
    {"ticker": "IWP",  "name": "iShares Russell Mid-Cap Growth ETF",         "category": "US Mid Cap"},
    {"ticker": "IWS",  "name": "iShares Russell Mid-Cap Value ETF",          "category": "US Mid Cap"},

    # ── US SMALL CAP ─────────────────────────────────────────────────────────
    {"ticker": "IJR",  "name": "iShares Core S&P Small-Cap ETF",             "category": "US Small Cap"},
    {"ticker": "IWM",  "name": "iShares Russell 2000 ETF",                   "category": "US Small Cap"},
    {"ticker": "VB",   "name": "Vanguard Small-Cap ETF",                     "category": "US Small Cap"},
    {"ticker": "SLY",  "name": "SPDR S&P 600 Small Cap ETF",                 "category": "US Small Cap"},
    {"ticker": "SCHA", "name": "Schwab US Small-Cap ETF",                    "category": "US Small Cap"},
    {"ticker": "IJS",  "name": "iShares S&P Small-Cap 600 Value ETF",        "category": "US Small Cap"},
    {"ticker": "IJT",  "name": "iShares S&P Small-Cap 600 Growth ETF",       "category": "US Small Cap"},
    {"ticker": "VTWO", "name": "Vanguard Russell 2000 ETF",                  "category": "US Small Cap"},
    {"ticker": "IWC",  "name": "iShares Micro-Cap ETF",                      "category": "US Small Cap"},
    {"ticker": "DFAS", "name": "Dimensional US Small Cap ETF",               "category": "US Small Cap"},

    # ── INTERNATIONAL DEVELOPED ──────────────────────────────────────────────
    {"ticker": "VEA",  "name": "Vanguard FTSE Developed Markets ETF",        "category": "Intl Developed"},
    {"ticker": "EFA",  "name": "iShares MSCI EAFE ETF",                      "category": "Intl Developed"},
    {"ticker": "IEFA", "name": "iShares Core MSCI EAFE ETF",                 "category": "Intl Developed"},
    {"ticker": "SPDW", "name": "SPDR Portfolio Developed World ex-US ETF",   "category": "Intl Developed"},
    {"ticker": "SCHF", "name": "Schwab International Equity ETF",            "category": "Intl Developed"},
    {"ticker": "VEU",  "name": "Vanguard FTSE All-World ex-US ETF",          "category": "Intl Developed"},
    {"ticker": "VXUS", "name": "Vanguard Total International Stock ETF",     "category": "Intl Developed"},
    {"ticker": "VT",   "name": "Vanguard Total World Stock ETF",             "category": "Global"},
    {"ticker": "ACWI", "name": "iShares MSCI ACWI ETF",                     "category": "Global"},
    {"ticker": "IXUS", "name": "iShares Core MSCI Total International ETF",  "category": "Intl Developed"},
    {"ticker": "EFAV", "name": "iShares MSCI EAFE Min Vol Factor ETF",       "category": "Intl Developed"},
    {"ticker": "ESGD", "name": "iShares ESG Aware MSCI EAFE ETF",           "category": "Intl Developed"},
    {"ticker": "BBEU", "name": "JPMorgan BetaBuilders Europe ETF",           "category": "Europe"},
    {"ticker": "VGK",  "name": "Vanguard FTSE Europe ETF",                   "category": "Europe"},
    {"ticker": "IEV",  "name": "iShares Europe ETF",                         "category": "Europe"},
    {"ticker": "EWU",  "name": "iShares MSCI United Kingdom ETF",            "category": "Europe"},
    {"ticker": "EWG",  "name": "iShares MSCI Germany ETF",                   "category": "Europe"},
    {"ticker": "EWQ",  "name": "iShares MSCI France ETF",                    "category": "Europe"},
    {"ticker": "EWI",  "name": "iShares MSCI Italy ETF",                     "category": "Europe"},
    {"ticker": "EWP",  "name": "iShares MSCI Spain ETF",                     "category": "Europe"},
    {"ticker": "EWN",  "name": "iShares MSCI Netherlands ETF",               "category": "Europe"},
    {"ticker": "EWO",  "name": "iShares MSCI Austria ETF",                   "category": "Europe"},
    {"ticker": "EWK",  "name": "iShares MSCI Belgium ETF",                   "category": "Europe"},
    {"ticker": "EWD",  "name": "iShares MSCI Sweden ETF",                    "category": "Europe"},
    {"ticker": "EWL",  "name": "iShares MSCI Switzerland ETF",               "category": "Europe"},
    {"ticker": "EWJ",  "name": "iShares MSCI Japan ETF",                     "category": "Asia Pacific"},
    {"ticker": "DXJ",  "name": "WisdomTree Japan Hedged Equity ETF",         "category": "Asia Pacific"},
    {"ticker": "EWA",  "name": "iShares MSCI Australia ETF",                 "category": "Asia Pacific"},
    {"ticker": "EWC",  "name": "iShares MSCI Canada ETF",                    "category": "North America"},
    {"ticker": "VPL",  "name": "Vanguard FTSE Pacific ETF",                  "category": "Asia Pacific"},
    {"ticker": "EPP",  "name": "iShares MSCI Pacific ex Japan ETF",          "category": "Asia Pacific"},
    {"ticker": "EWS",  "name": "iShares MSCI Singapore ETF",                 "category": "Asia Pacific"},
    {"ticker": "EWH",  "name": "iShares MSCI Hong Kong ETF",                 "category": "Asia Pacific"},

    # ── EMERGING MARKETS ─────────────────────────────────────────────────────
    {"ticker": "VWO",  "name": "Vanguard FTSE Emerging Markets ETF",         "category": "Emerging Markets"},
    {"ticker": "EEM",  "name": "iShares MSCI Emerging Markets ETF",          "category": "Emerging Markets"},
    {"ticker": "IEMG", "name": "iShares Core MSCI Emerging Markets ETF",     "category": "Emerging Markets"},
    {"ticker": "SCHE", "name": "Schwab Emerging Markets Equity ETF",         "category": "Emerging Markets"},
    {"ticker": "SPEM", "name": "SPDR Portfolio Emerging Markets ETF",        "category": "Emerging Markets"},
    {"ticker": "FNDE", "name": "Schwab Fundamental EM Large Company ETF",    "category": "Emerging Markets"},
    {"ticker": "DEM",  "name": "WisdomTree Emerging Markets High Dividend ETF","category": "Emerging Markets"},
    {"ticker": "EEMV", "name": "iShares MSCI Emerging Mkts Min Vol ETF",     "category": "Emerging Markets"},
    {"ticker": "FXI",  "name": "iShares China Large-Cap ETF",                "category": "China"},
    {"ticker": "MCHI", "name": "iShares MSCI China ETF",                     "category": "China"},
    {"ticker": "KWEB", "name": "KraneShares CSI China Internet ETF",         "category": "China"},
    {"ticker": "CQQQ", "name": "Invesco China Technology ETF",               "category": "China"},
    {"ticker": "GXC",  "name": "SPDR S&P China ETF",                         "category": "China"},
    {"ticker": "INDA", "name": "iShares MSCI India ETF",                     "category": "India"},
    {"ticker": "INDY", "name": "iShares India 50 ETF",                       "category": "India"},
    {"ticker": "PIN",  "name": "Invesco India ETF",                          "category": "India"},
    {"ticker": "EWY",  "name": "iShares MSCI South Korea ETF",               "category": "Emerging Markets"},
    {"ticker": "EWT",  "name": "iShares MSCI Taiwan ETF",                    "category": "Emerging Markets"},
    {"ticker": "EWZ",  "name": "iShares MSCI Brazil ETF",                    "category": "Emerging Markets"},
    {"ticker": "EWM",  "name": "iShares MSCI Malaysia ETF",                  "category": "Emerging Markets"},
    {"ticker": "THD",  "name": "iShares MSCI Thailand ETF",                  "category": "Emerging Markets"},
    {"ticker": "EPHE", "name": "iShares MSCI Philippines ETF",               "category": "Emerging Markets"},

    # ── SECTOR ETFs ──────────────────────────────────────────────────────────
    {"ticker": "XLK",  "name": "Technology Select Sector SPDR Fund",         "category": "Technology"},
    {"ticker": "VGT",  "name": "Vanguard Information Technology ETF",        "category": "Technology"},
    {"ticker": "IYW",  "name": "iShares US Technology ETF",                  "category": "Technology"},
    {"ticker": "IGV",  "name": "iShares Expanded Tech-Software Sector ETF",  "category": "Technology"},
    {"ticker": "SKYY", "name": "First Trust Cloud Computing ETF",            "category": "Technology"},
    {"ticker": "WCLD", "name": "WisdomTree Cloud Computing ETF",             "category": "Technology"},
    {"ticker": "CLOU", "name": "Global X Cloud Computing ETF",               "category": "Technology"},
    {"ticker": "BUG",  "name": "Global X Cybersecurity ETF",                 "category": "Technology"},
    {"ticker": "CIBR", "name": "First Trust Nasdaq Cybersecurity ETF",       "category": "Technology"},
    {"ticker": "HACK", "name": "ETFMG Prime Cyber Security ETF",             "category": "Technology"},
    {"ticker": "ROBO", "name": "Robo Global Robotics & Automation ETF",      "category": "Technology"},
    {"ticker": "BOTZ", "name": "Global X Robotics & Artificial Intelligence ETF","category": "Technology"},
    {"ticker": "SOXX", "name": "iShares Semiconductor ETF",                  "category": "Technology"},
    {"ticker": "SMH",  "name": "VanEck Semiconductor ETF",                   "category": "Technology"},
    {"ticker": "XSD",  "name": "SPDR S&P Semiconductor ETF",                 "category": "Technology"},
    {"ticker": "XLF",  "name": "Financial Select Sector SPDR Fund",          "category": "Financials"},
    {"ticker": "VFH",  "name": "Vanguard Financials ETF",                    "category": "Financials"},
    {"ticker": "IYF",  "name": "iShares US Financials ETF",                  "category": "Financials"},
    {"ticker": "IYG",  "name": "iShares US Financial Services ETF",          "category": "Financials"},
    {"ticker": "KBE",  "name": "SPDR S&P Bank ETF",                          "category": "Financials"},
    {"ticker": "KRE",  "name": "SPDR S&P Regional Banking ETF",              "category": "Financials"},
    {"ticker": "IAT",  "name": "iShares US Regional Banks ETF",              "category": "Financials"},
    {"ticker": "IAI",  "name": "iShares US Broker-Dealers & Securities ETF", "category": "Financials"},
    {"ticker": "XLV",  "name": "Health Care Select Sector SPDR Fund",        "category": "Healthcare"},
    {"ticker": "VHT",  "name": "Vanguard Health Care ETF",                   "category": "Healthcare"},
    {"ticker": "IYH",  "name": "iShares US Healthcare ETF",                  "category": "Healthcare"},
    {"ticker": "IHF",  "name": "iShares US Healthcare Providers ETF",        "category": "Healthcare"},
    {"ticker": "IBB",  "name": "iShares Biotechnology ETF",                  "category": "Healthcare"},
    {"ticker": "XBI",  "name": "SPDR S&P Biotech ETF",                       "category": "Healthcare"},
    {"ticker": "IHI",  "name": "iShares US Medical Devices ETF",             "category": "Healthcare"},
    {"ticker": "ARKG", "name": "ARK Genomic Revolution ETF",                 "category": "Healthcare"},
    {"ticker": "XLY",  "name": "Consumer Discret Select Sector SPDR Fund",   "category": "Consumer Discret"},
    {"ticker": "VCR",  "name": "Vanguard Consumer Discretionary ETF",        "category": "Consumer Discret"},
    {"ticker": "IYC",  "name": "iShares US Consumer Discretionary ETF",      "category": "Consumer Discret"},
    {"ticker": "PEJ",  "name": "Invesco Dynamic Leisure and Entertainment ETF","category": "Consumer Discret"},
    {"ticker": "RETL", "name": "Direxion Daily Retail Bull 3X Shares",       "category": "Consumer Discret"},
    {"ticker": "XLP",  "name": "Consumer Staples Select Sector SPDR Fund",   "category": "Consumer Staples"},
    {"ticker": "VDC",  "name": "Vanguard Consumer Staples ETF",              "category": "Consumer Staples"},
    {"ticker": "IYK",  "name": "iShares US Consumer Staples ETF",            "category": "Consumer Staples"},
    {"ticker": "XLE",  "name": "Energy Select Sector SPDR Fund",             "category": "Energy"},
    {"ticker": "VDE",  "name": "Vanguard Energy ETF",                        "category": "Energy"},
    {"ticker": "IYE",  "name": "iShares US Energy ETF",                      "category": "Energy"},
    {"ticker": "XOP",  "name": "SPDR S&P Oil & Gas Explor & Prodtn ETF",    "category": "Energy"},
    {"ticker": "OIH",  "name": "VanEck Oil Services ETF",                    "category": "Energy"},
    {"ticker": "AMLP", "name": "Alerian MLP ETF",                            "category": "Energy"},
    {"ticker": "XLB",  "name": "Materials Select Sector SPDR Fund",          "category": "Materials"},
    {"ticker": "VAW",  "name": "Vanguard Materials ETF",                     "category": "Materials"},
    {"ticker": "IYM",  "name": "iShares US Basic Materials ETF",             "category": "Materials"},
    {"ticker": "LIT",  "name": "Global X Lithium & Battery Tech ETF",        "category": "Materials"},
    {"ticker": "REMX", "name": "VanEck Rare Earth/Strategic Metals ETF",     "category": "Materials"},
    {"ticker": "XLU",  "name": "Utilities Select Sector SPDR Fund",          "category": "Utilities"},
    {"ticker": "VPU",  "name": "Vanguard Utilities ETF",                     "category": "Utilities"},
    {"ticker": "IDU",  "name": "iShares US Utilities ETF",                   "category": "Utilities"},
    {"ticker": "FUTY", "name": "Fidelity MSCI Utilities Index ETF",          "category": "Utilities"},
    {"ticker": "VNQ",  "name": "Vanguard Real Estate ETF",                   "category": "Real Estate"},
    {"ticker": "IYR",  "name": "iShares US Real Estate ETF",                 "category": "Real Estate"},
    {"ticker": "XLRE", "name": "Real Estate Select Sector SPDR Fund",        "category": "Real Estate"},
    {"ticker": "SCHH", "name": "Schwab US REIT ETF",                         "category": "Real Estate"},
    {"ticker": "REM",  "name": "iShares Mortgage Real Estate ETF",           "category": "Real Estate"},
    {"ticker": "MORT", "name": "VanEck Mortgage REIT Income ETF",            "category": "Real Estate"},
    {"ticker": "XLC",  "name": "Communication Services Select Sector SPDR",  "category": "Comm Services"},
    {"ticker": "VOX",  "name": "Vanguard Communication Services ETF",        "category": "Comm Services"},
    {"ticker": "IYZ",  "name": "iShares US Telecommunications ETF",          "category": "Comm Services"},
    {"ticker": "XLI",  "name": "Industrial Select Sector SPDR Fund",         "category": "Industrials"},
    {"ticker": "VIS",  "name": "Vanguard Industrials ETF",                   "category": "Industrials"},
    {"ticker": "IYT",  "name": "iShares US Transportation ETF",              "category": "Industrials"},
    {"ticker": "JETS", "name": "US Global Jets ETF",                         "category": "Industrials"},
    {"ticker": "CARZ", "name": "First Trust S-Network Future Vehicles ETF",  "category": "Industrials"},

    # ── FIXED INCOME ─────────────────────────────────────────────────────────
    {"ticker": "BND",  "name": "Vanguard Total Bond Market ETF",             "category": "Bonds"},
    {"ticker": "AGG",  "name": "iShares Core US Aggregate Bond ETF",         "category": "Bonds"},
    {"ticker": "SPAB", "name": "SPDR Portfolio Aggregate Bond ETF",          "category": "Bonds"},
    {"ticker": "SCHZ", "name": "Schwab US Aggregate Bond ETF",               "category": "Bonds"},
    {"ticker": "FBND", "name": "Fidelity Total Bond ETF",                    "category": "Bonds"},
    {"ticker": "BSV",  "name": "Vanguard Short-Term Bond ETF",               "category": "Bonds Short"},
    {"ticker": "VCSH", "name": "Vanguard Short-Term Corporate Bond ETF",     "category": "Bonds Short"},
    {"ticker": "SPSB", "name": "SPDR Portfolio Short Term Corporate Bond ETF","category": "Bonds Short"},
    {"ticker": "SHY",  "name": "iShares 1-3 Year Treasury Bond ETF",         "category": "Bonds Short"},
    {"ticker": "BIL",  "name": "SPDR Bloomberg 1-3 Month T-Bill ETF",        "category": "Bonds Short"},
    {"ticker": "SGOV", "name": "iShares 0-3 Month Treasury Bond ETF",        "category": "Bonds Short"},
    {"ticker": "SCHO", "name": "Schwab Short-Term US Treasury ETF",          "category": "Bonds Short"},
    {"ticker": "BIV",  "name": "Vanguard Intermediate-Term Bond ETF",        "category": "Bonds Inter"},
    {"ticker": "VCIT", "name": "Vanguard Intermediate-Term Corporate Bond ETF","category": "Bonds Inter"},
    {"ticker": "SPIB", "name": "SPDR Portfolio Intermediate Term Corp Bond ETF","category": "Bonds Inter"},
    {"ticker": "IEF",  "name": "iShares 7-10 Year Treasury Bond ETF",        "category": "Bonds Inter"},
    {"ticker": "GOVT", "name": "iShares US Treasury Bond ETF",               "category": "Bonds Inter"},
    {"ticker": "BLV",  "name": "Vanguard Long-Term Bond ETF",                "category": "Bonds Long"},
    {"ticker": "VCLT", "name": "Vanguard Long-Term Corporate Bond ETF",      "category": "Bonds Long"},
    {"ticker": "SPLB", "name": "SPDR Portfolio Long Term Corporate Bond ETF", "category": "Bonds Long"},
    {"ticker": "TLT",  "name": "iShares 20+ Year Treasury Bond ETF",         "category": "Bonds Long"},
    {"ticker": "EDV",  "name": "Vanguard Extended Duration Treasury ETF",    "category": "Bonds Long"},
    {"ticker": "ZROZ", "name": "PIMCO 25+ Year Zero Coupon US Treasury ETF", "category": "Bonds Long"},
    {"ticker": "VTIP", "name": "Vanguard Short-Term Inflation-Protected ETF", "category": "TIPS"},
    {"ticker": "STIP", "name": "iShares 0-5 Year TIPS Bond ETF",             "category": "TIPS"},
    {"ticker": "TIP",  "name": "iShares TIPS Bond ETF",                      "category": "TIPS"},
    {"ticker": "SCHP", "name": "Schwab US TIPS ETF",                         "category": "TIPS"},
    {"ticker": "LTPZ", "name": "PIMCO 15+ Year US TIPS Index ETF",           "category": "TIPS"},
    {"ticker": "HYG",  "name": "iShares iBoxx $ High Yield Corporate Bond ETF","category": "High Yield"},
    {"ticker": "JNK",  "name": "SPDR Bloomberg High Yield Bond ETF",         "category": "High Yield"},
    {"ticker": "SPHY", "name": "SPDR Portfolio High Yield Bond ETF",         "category": "High Yield"},
    {"ticker": "USHY", "name": "iShares Broad USD High Yield Corporate Bond ETF","category": "High Yield"},
    {"ticker": "HYD",  "name": "VanEck High Yield Muni ETF",                 "category": "High Yield"},
    {"ticker": "FALN", "name": "iShares Fallen Angels USD Bond ETF",         "category": "High Yield"},
    {"ticker": "BNDX", "name": "Vanguard Total International Bond ETF",      "category": "Intl Bonds"},
    {"ticker": "IAGG", "name": "iShares Core International Aggregate Bond ETF","category": "Intl Bonds"},
    {"ticker": "EMB",  "name": "iShares JPMorgan USD Emerging Markets Bond ETF","category": "Intl Bonds"},
    {"ticker": "PCY",  "name": "Invesco Emerging Markets Sovereign Debt ETF","category": "Intl Bonds"},
    {"ticker": "VWOB", "name": "Vanguard Emerging Markets Government Bond ETF","category": "Intl Bonds"},
    {"ticker": "LQD",  "name": "iShares iBoxx $ Investment Grade Corporate Bond ETF","category": "Corp Bonds"},
    {"ticker": "VCOR", "name": "Vanguard Core Bond ETF",                     "category": "Corp Bonds"},
    {"ticker": "MBB",  "name": "iShares MBS ETF",                            "category": "Corp Bonds"},
    {"ticker": "VMBS", "name": "Vanguard Mortgage-Backed Securities ETF",    "category": "Corp Bonds"},

    # ── COMMODITIES & ALTERNATIVES ───────────────────────────────────────────
    {"ticker": "GLD",  "name": "SPDR Gold Shares",                           "category": "Commodities"},
    {"ticker": "GLDM", "name": "SPDR Gold MiniShares Trust",                 "category": "Commodities"},
    {"ticker": "IAU",  "name": "iShares Gold Trust",                         "category": "Commodities"},
    {"ticker": "SGOL", "name": "Aberdeen Standard Physical Gold Shares ETF", "category": "Commodities"},
    {"ticker": "OUNZ", "name": "VanEck Merk Gold ETF",                       "category": "Commodities"},
    {"ticker": "SLV",  "name": "iShares Silver Trust",                       "category": "Commodities"},
    {"ticker": "SIVR", "name": "Aberdeen Standard Physical Silver Shares ETF","category": "Commodities"},
    {"ticker": "PPLT", "name": "Aberdeen Standard Physical Platinum ETF",    "category": "Commodities"},
    {"ticker": "PALL", "name": "Aberdeen Standard Physical Palladium ETF",   "category": "Commodities"},
    {"ticker": "GDX",  "name": "VanEck Gold Miners ETF",                     "category": "Commodities"},
    {"ticker": "GDXJ", "name": "VanEck Junior Gold Miners ETF",              "category": "Commodities"},
    {"ticker": "RING", "name": "iShares MSCI Global Gold Miners ETF",        "category": "Commodities"},
    {"ticker": "PICK", "name": "iShares MSCI Global Metals & Mining Producers ETF","category": "Commodities"},
    {"ticker": "USO",  "name": "United States Oil Fund",                     "category": "Commodities"},
    {"ticker": "BNO",  "name": "United States Brent Oil Fund",               "category": "Commodities"},
    {"ticker": "DBC",  "name": "Invesco DB Commodity Index Tracking Fund",   "category": "Commodities"},
    {"ticker": "PDBC", "name": "Invesco Optimum Yield Diversified Commodity No K-1 ETF","category": "Commodities"},
    {"ticker": "DJP",  "name": "iPath Bloomberg Commodity Index Total Return ETN","category": "Commodities"},
    {"ticker": "COMB", "name": "GraniteShares Bloomberg Commodity Broad Strategy No K-1 ETF","category": "Commodities"},
    {"ticker": "UNG",  "name": "United States Natural Gas Fund",             "category": "Commodities"},
    {"ticker": "CORN", "name": "Teucrium Corn Fund",                         "category": "Commodities"},
    {"ticker": "WEAT", "name": "Teucrium Wheat Fund",                        "category": "Commodities"},
    {"ticker": "SOYB", "name": "Teucrium Soybean Fund",                      "category": "Commodities"},
    {"ticker": "CANE", "name": "Teucrium Sugar Fund",                        "category": "Commodities"},
    {"ticker": "BAL",  "name": "iPath Bloomberg Cotton Subindex Total Return ETN","category": "Commodities"},
    {"ticker": "COW",  "name": "iPath Bloomberg Livestock Subindex Total Return ETN","category": "Commodities"},
    {"ticker": "COPX", "name": "Global X Copper Miners ETF",                 "category": "Commodities"},
    {"ticker": "CPER", "name": "United States Copper Index Fund",            "category": "Commodities"},

    # ── THEMATIC / INNOVATION ────────────────────────────────────────────────
    {"ticker": "ARKK", "name": "ARK Innovation ETF",                         "category": "Thematic"},
    {"ticker": "ARKW", "name": "ARK Next Generation Internet ETF",           "category": "Thematic"},
    {"ticker": "ARKQ", "name": "ARK Autonomous Technology & Robotics ETF",   "category": "Thematic"},
    {"ticker": "ARKF", "name": "ARK Fintech Innovation ETF",                 "category": "Thematic"},
    {"ticker": "ARKX", "name": "ARK Space Exploration & Innovation ETF",     "category": "Thematic"},
    {"ticker": "MOON", "name": "Direxion Moonshot Innovators ETF",           "category": "Thematic"},
    {"ticker": "UFO",  "name": "Procure Space ETF",                          "category": "Thematic"},
    {"ticker": "ROKT", "name": "MomentumX ETF",                              "category": "Thematic"},
    {"ticker": "BLOK", "name": "Amplify Transformational Data Sharing ETF",  "category": "Thematic"},
    {"ticker": "BKCH", "name": "Global X Blockchain ETF",                    "category": "Thematic"},
    {"ticker": "ICLN", "name": "iShares Global Clean Energy ETF",            "category": "Clean Energy"},
    {"ticker": "QCLN", "name": "First Trust Nasdaq Clean Edge Green Energy ETF","category": "Clean Energy"},
    {"ticker": "TAN",  "name": "Invesco Solar ETF",                          "category": "Clean Energy"},
    {"ticker": "FAN",  "name": "First Trust Global Wind Energy ETF",         "category": "Clean Energy"},
    {"ticker": "CNRG", "name": "SPDR S&P Kensho Clean Power ETF",            "category": "Clean Energy"},
    {"ticker": "PBW",  "name": "Invesco WilderHill Clean Energy ETF",        "category": "Clean Energy"},
    {"ticker": "SMOG", "name": "VanEck Low Carbon Energy ETF",               "category": "Clean Energy"},
    {"ticker": "DRIV", "name": "Global X Autonomous & Electric Vehicles ETF","category": "Thematic"},
    {"ticker": "KARS", "name": "KraneShares Electric Vehicles & Future Mobility ETF","category": "Thematic"},
    {"ticker": "LIT",  "name": "Global X Lithium & Battery Tech ETF",        "category": "Thematic"},
    {"ticker": "MSOS", "name": "AdvisorShares Pure US Cannabis ETF",         "category": "Thematic"},
    {"ticker": "MJ",   "name": "ETFMG Alternative Harvest ETF",              "category": "Thematic"},
    {"ticker": "GAMR", "name": "Wedbush ETFMG Video Game Tech ETF",          "category": "Thematic"},
    {"ticker": "ESPO", "name": "VanEck Video Gaming and eSports ETF",        "category": "Thematic"},
    {"ticker": "HERO", "name": "Global X Video Games & Esports ETF",         "category": "Thematic"},
    {"ticker": "FINX", "name": "Global X FinTech ETF",                       "category": "Thematic"},
    {"ticker": "IPAY", "name": "ETFMG Prime Mobile Payments ETF",            "category": "Thematic"},
    {"ticker": "GNOM", "name": "Global X Genomics & Biotechnology ETF",      "category": "Thematic"},
    {"ticker": "IDNA", "name": "iShares Genomics Immunology and Healthcare ETF","category": "Thematic"},
    {"ticker": "IBOT", "name": "iShares Robotics and Artificial Intelligence Multisector ETF","category": "Thematic"},
    {"ticker": "TPVG", "name": "TriplePoint Venture Growth BDC Corp",        "category": "Thematic"},
    {"ticker": "METV", "name": "Roundhill Ball Metaverse ETF",               "category": "Thematic"},
    {"ticker": "VR",   "name": "Tuttle Capital Virtual Reality ETF",          "category": "Thematic"},
    {"ticker": "AIQ",  "name": "Global X Artificial Intelligence & Technology ETF","category": "Thematic"},
    {"ticker": "LRNZ", "name": "TrueShares Technology, AI & Deep Learning ETF","category": "Thematic"},
    {"ticker": "QTUM", "name": "Defiance Quantum ETF",                       "category": "Thematic"},
    {"ticker": "BETZ", "name": "Roundhill Sports Betting & iGaming ETF",     "category": "Thematic"},
    {"ticker": "BFIT", "name": "Global X Health & Wellness ETF",             "category": "Thematic"},
    {"ticker": "EDUT", "name": "Global X Education ETF",                     "category": "Thematic"},
    {"ticker": "CATH", "name": "Global X S&P 500 Catholic Values ETF",       "category": "Thematic"},

    # ── ESG / SUSTAINABLE ────────────────────────────────────────────────────
    {"ticker": "ESGV", "name": "Vanguard ESG US Stock ETF",                  "category": "ESG"},
    {"ticker": "ESGU", "name": "iShares MSCI USA ESG Optimized ETF",         "category": "ESG"},
    {"ticker": "DSI",  "name": "iShares MSCI KLD 400 Social ETF",            "category": "ESG"},
    {"ticker": "SUSA", "name": "iShares MSCI USA ESG Select ETF",            "category": "ESG"},
    {"ticker": "KRMA", "name": "Global X Conscious Companies ETF",           "category": "ESG"},
    {"ticker": "VEGN", "name": "US Vegan Climate ETF",                       "category": "ESG"},
    {"ticker": "NULG", "name": "Nuveen ESG Large-Cap Growth ETF",            "category": "ESG"},
    {"ticker": "NULV", "name": "Nuveen ESG Large-Cap Value ETF",             "category": "ESG"},
    {"ticker": "SUSB", "name": "iShares ESG Aware 1-5 Year USD Corporate Bond ETF","category": "ESG"},
    {"ticker": "SUSC", "name": "iShares ESG Aware USD Corporate Bond ETF",   "category": "ESG"},

    # ── LEVERAGED / INVERSE (1.5x-2x only — less extreme) ──────────────────
    {"ticker": "SSO",  "name": "ProShares Ultra S&P 500 (2x)",               "category": "Leveraged"},
    {"ticker": "QLD",  "name": "ProShares Ultra QQQ (2x)",                   "category": "Leveraged"},
    {"ticker": "UWM",  "name": "ProShares Ultra Russell 2000 (2x)",          "category": "Leveraged"},
    {"ticker": "ROM",  "name": "ProShares Ultra Technology (2x)",            "category": "Leveraged"},
    {"ticker": "UYG",  "name": "ProShares Ultra Financials (2x)",            "category": "Leveraged"},
    {"ticker": "RXL",  "name": "ProShares Ultra Health Care (2x)",           "category": "Leveraged"},
    {"ticker": "EET",  "name": "ProShares Ultra MSCI Emerging Markets (2x)", "category": "Leveraged"},
    {"ticker": "EFO",  "name": "ProShares Ultra MSCI EAFE (2x)",             "category": "Leveraged"},
    {"ticker": "UGL",  "name": "ProShares Ultra Gold (2x)",                  "category": "Leveraged"},
    {"ticker": "AGQ",  "name": "ProShares Ultra Silver (2x)",                "category": "Leveraged"},
    {"ticker": "UCO",  "name": "ProShares Ultra Bloomberg Crude Oil (2x)",   "category": "Leveraged"},

    # ── MULTI-ASSET / BALANCED ───────────────────────────────────────────────
    {"ticker": "AOR",  "name": "iShares Core Growth Allocation ETF",         "category": "Multi-Asset"},
    {"ticker": "AOM",  "name": "iShares Core Moderate Allocation ETF",       "category": "Multi-Asset"},
    {"ticker": "AOA",  "name": "iShares Core Aggressive Allocation ETF",     "category": "Multi-Asset"},
    {"ticker": "AOK",  "name": "iShares Core Conservative Allocation ETF",   "category": "Multi-Asset"},
    {"ticker": "VSMGX","name": "Vanguard LifeStrategy Moderate Growth Fund", "category": "Multi-Asset"},
    {"ticker": "TRRIX","name": "T. Rowe Price Retirement Income Fund",       "category": "Multi-Asset"},
    {"ticker": "GAL",  "name": "SPDR SSgA Global Allocation ETF",            "category": "Multi-Asset"},
    {"ticker": "ONEF", "name": "SPDR Russell 1000 Momentum Focus ETF",       "category": "Multi-Asset"},
    {"ticker": "GMOM", "name": "Cambria Global Momentum ETF",                "category": "Multi-Asset"},
    {"ticker": "GVAL", "name": "Cambria Global Value ETF",                   "category": "Multi-Asset"},
    {"ticker": "GQRE", "name": "FlexShares Global Quality Real Estate Index Fund","category": "Multi-Asset"},

    # ── ADDITIONAL REGIONAL ──────────────────────────────────────────────────
    {"ticker": "EZU",  "name": "iShares MSCI Eurozone ETF",                  "category": "Europe"},
    {"ticker": "HEDJ", "name": "WisdomTree Europe Hedged Equity ETF",        "category": "Europe"},
    {"ticker": "DBEF", "name": "Xtrackers MSCI EAFE Hedged Equity ETF",      "category": "Intl Developed"},
    {"ticker": "DBJP", "name": "Xtrackers MSCI Japan Hedged Equity ETF",     "category": "Asia Pacific"},
    {"ticker": "HEWJ", "name": "iShares Currency Hedged MSCI Japan ETF",     "category": "Asia Pacific"},
    {"ticker": "HEFA", "name": "iShares Currency Hedged MSCI EAFE ETF",      "category": "Intl Developed"},
    {"ticker": "GEM",  "name": "Goldman Sachs ActiveBeta Emerging Mkts ETF", "category": "Emerging Markets"},
    {"ticker": "FRDM", "name": "Freedom 100 Emerging Markets ETF",           "category": "Emerging Markets"},
    {"ticker": "VGK",  "name": "Vanguard FTSE Europe ETF",                   "category": "Europe"},
    {"ticker": "EWF",  "name": "iShares MSCI Finland Capped ETF",            "category": "Europe"},
    {"ticker": "ENOR", "name": "iShares MSCI Norway ETF",                    "category": "Europe"},
    {"ticker": "EDEN", "name": "iShares MSCI Denmark ETF",                   "category": "Europe"},
    {"ticker": "EWE",  "name": "iShares MSCI New Zealand ETF",               "category": "Asia Pacific"},
    {"ticker": "ERUS", "name": "iShares MSCI Russia ETF",                    "category": "Emerging Markets"},
    {"ticker": "EWW",  "name": "iShares MSCI Mexico ETF",                    "category": "Latin America"},
    {"ticker": "ECH",  "name": "iShares MSCI Chile ETF",                     "category": "Latin America"},
    {"ticker": "EPU",  "name": "iShares MSCI Peru ETF",                      "category": "Latin America"},
    {"ticker": "ICOL", "name": "iShares MSCI Colombia ETF",                  "category": "Latin America"},
    {"ticker": "ARGT", "name": "Global X MSCI Argentina ETF",                "category": "Latin America"},
    {"ticker": "ILF",  "name": "iShares Latin America 40 ETF",               "category": "Latin America"},
    {"ticker": "EWJ",  "name": "iShares MSCI Japan ETF",                     "category": "Asia Pacific"},
    {"ticker": "EIDO", "name": "iShares MSCI Indonesia ETF",                 "category": "Asia Pacific"},
    {"ticker": "EWX",  "name": "SPDR S&P Emerging Markets Small Cap ETF",    "category": "Emerging Markets"},
    {"ticker": "XSOE", "name": "WisdomTree Emerging Markets ex-State-Owned Enterprises ETF","category": "Emerging Markets"},
    {"ticker": "EMGF", "name": "iShares MSCI Emerging Markets Min Vol Factor ETF","category": "Emerging Markets"},
    {"ticker": "VNQI", "name": "Vanguard Global ex-US Real Estate ETF",      "category": "Real Estate"},
    {"ticker": "HAUZ", "name": "Xtrackers International Real Estate ETF",    "category": "Real Estate"},
    {"ticker": "IFGL", "name": "iShares International Developed Real Estate ETF","category": "Real Estate"},
    {"ticker": "RWX",  "name": "SPDR DJ Wilshire Intl Real Estate ETF",      "category": "Real Estate"},

    # ── ADDITIONAL FIXED INCOME ──────────────────────────────────────────────
    {"ticker": "BNDW", "name": "Vanguard Total World Bond ETF",              "category": "Bonds"},
    {"ticker": "GTO",  "name": "Invesco Total Return Bond ETF",              "category": "Bonds"},
    {"ticker": "TOTL", "name": "SPDR DoubleLine Total Return Tactical ETF",  "category": "Bonds"},
    {"ticker": "NEAR", "name": "iShares Short Maturity Bond ETF",            "category": "Bonds Short"},
    {"ticker": "MINT", "name": "PIMCO Enhanced Short Maturity Active ETF",   "category": "Bonds Short"},
    {"ticker": "JPST", "name": "JPMorgan Ultra-Short Income ETF",            "category": "Bonds Short"},
    {"ticker": "GSY",  "name": "Invesco Ultra Short Duration ETF",           "category": "Bonds Short"},
    {"ticker": "FLOT", "name": "iShares Floating Rate Bond ETF",             "category": "Bonds"},
    {"ticker": "FLRN", "name": "SPDR Bloomberg Investment Grade Floating Rate ETF","category": "Bonds"},
    {"ticker": "BKLN", "name": "Invesco Senior Loan ETF",                    "category": "Bonds"},
    {"ticker": "SRLN", "name": "SPDR Blackstone Senior Loan ETF",            "category": "Bonds"},
    {"ticker": "HYEM", "name": "VanEck Emerging Markets High Yield Bond ETF","category": "Intl Bonds"},
    {"ticker": "EMHY", "name": "iShares J.P. Morgan EM High Yield Bond ETF", "category": "Intl Bonds"},
    {"ticker": "EBND", "name": "SPDR Bloomberg Barclays Emerging Markets Local Bond ETF","category": "Intl Bonds"},
    {"ticker": "LEMB", "name": "iShares JPMorgan EM Local Currency Bond ETF","category": "Intl Bonds"},
    {"ticker": "ELD",  "name": "WisdomTree Emerging Markets Local Debt ETF", "category": "Intl Bonds"},
    {"ticker": "MUB",  "name": "iShares National Muni Bond ETF",             "category": "Municipal"},
    {"ticker": "VTEB", "name": "Vanguard Tax-Exempt Bond ETF",               "category": "Municipal"},
    {"ticker": "SUB",  "name": "iShares Short-Term National Muni Bond ETF",  "category": "Municipal"},
    {"ticker": "ITOT", "name": "iShares Core S&P Total US Stock Market ETF", "category": "US Large Cap"},
    {"ticker": "CMF",  "name": "iShares California Muni Bond ETF",           "category": "Municipal"},
    {"ticker": "NYF",  "name": "iShares New York Muni Bond ETF",             "category": "Municipal"},

    # ── PREFERRED & CONVERTIBLE ──────────────────────────────────────────────
    {"ticker": "PFF",  "name": "iShares Preferred & Income Securities ETF",  "category": "Preferred"},
    {"ticker": "PFFD", "name": "Global X US Preferred ETF",                  "category": "Preferred"},
    {"ticker": "PSK",  "name": "SPDR Wells Fargo Preferred Stock ETF",       "category": "Preferred"},
    {"ticker": "FPE",  "name": "First Trust Preferred Securities & Income ETF","category": "Preferred"},
    {"ticker": "CWB",  "name": "SPDR Bloomberg Convertible Securities ETF",  "category": "Convertible"},
    {"ticker": "ICVT", "name": "iShares Convertible Bond ETF",               "category": "Convertible"},

    # ── DIVIDEND / INCOME ─────────────────────────────────────────────────────
    {"ticker": "SDOG", "name": "ALPS Sector Dividend Dogs ETF",              "category": "US Dividend"},
    {"ticker": "FDVV", "name": "Fidelity High Dividend ETF",                 "category": "US Dividend"},
    {"ticker": "FNDX", "name": "Schwab Fundamental US Large Company ETF",    "category": "US Large Cap"},
    {"ticker": "FNDF", "name": "Schwab Fundamental International Large Company ETF","category": "Intl Developed"},
    {"ticker": "FNDE", "name": "Schwab Fundamental Emerging Markets Large Company ETF","category": "Emerging Markets"},
    {"ticker": "VYMI", "name": "Vanguard International High Dividend Yield ETF","category": "Intl Dividend"},
    {"ticker": "DWX",  "name": "SPDR S&P International Dividend ETF",        "category": "Intl Dividend"},
    {"ticker": "IDV",  "name": "iShares International Select Dividend ETF",  "category": "Intl Dividend"},
    {"ticker": "DVYE", "name": "iShares Emerging Markets Dividend ETF",      "category": "Intl Dividend"},
    {"ticker": "DEM",  "name": "WisdomTree Emerging Markets High Dividend ETF","category": "Intl Dividend"},
    {"ticker": "EDIV", "name": "SPDR S&P Emerging Markets Dividend ETF",     "category": "Intl Dividend"},
    {"ticker": "QDIV", "name": "Global X S&P 500 Quality Dividend ETF",      "category": "US Dividend"},

    # ── ADDITIONAL SECTOR ────────────────────────────────────────────────────
    {"ticker": "PAVE", "name": "Global X US Infrastructure Development ETF", "category": "Industrials"},
    {"ticker": "TOLZ", "name": "ProShares DJ Brookfield Global Infrastructure ETF","category": "Industrials"},
    {"ticker": "GII",  "name": "SPDR S&P Global Infrastructure ETF",         "category": "Industrials"},
    {"ticker": "IGF",  "name": "iShares Global Infrastructure ETF",          "category": "Industrials"},
    {"ticker": "NFRA", "name": "FlexShares STOXX Global Broad Infrastructure ETF","category": "Industrials"},
    {"ticker": "WOOD", "name": "iShares Global Timber & Forestry ETF",       "category": "Materials"},
    {"ticker": "CUT",  "name": "Invesco MSCI Global Timber ETF",             "category": "Materials"},
    {"ticker": "SOIL", "name": "Global X AgTech & Food Innovation ETF",      "category": "Materials"},
    {"ticker": "HOGS", "name": "Portico Livestock ETF",                      "category": "Commodities"},
    {"ticker": "MOO",  "name": "VanEck Agribusiness ETF",                    "category": "Materials"},
    {"ticker": "VEGI", "name": "iShares MSCI Agriculture Producers ETF",     "category": "Materials"},
    {"ticker": "FILL", "name": "iShares MSCI Global Energy Producers ETF",   "category": "Energy"},
    {"ticker": "FCG",  "name": "First Trust Natural Gas ETF",                "category": "Energy"},
    {"ticker": "MLPA", "name": "Global X MLP ETF",                           "category": "Energy"},
    {"ticker": "AMZA", "name": "InfraCap MLP ETF",                           "category": "Energy"},
    {"ticker": "ENFR", "name": "Alerian Energy Infrastructure ETF",          "category": "Energy"},
    {"ticker": "KIE",  "name": "SPDR S&P Insurance ETF",                     "category": "Financials"},
    {"ticker": "IAK",  "name": "iShares US Insurance ETF",                   "category": "Financials"},
    {"ticker": "KBWP", "name": "Invesco KBW Property & Casualty Insurance ETF","category": "Financials"},
    {"ticker": "KBWY", "name": "Invesco KBW Premium Yield Equity REIT ETF",  "category": "Real Estate"},
    {"ticker": "KBWR", "name": "Invesco KBW Regional Banking ETF",           "category": "Financials"},
    {"ticker": "MSOS", "name": "AdvisorShares Pure US Cannabis ETF",         "category": "Thematic"},
    {"ticker": "PTF",  "name": "Invesco DWA Technology Momentum ETF",        "category": "Technology"},
    {"ticker": "PTH",  "name": "Invesco DWA Healthcare Momentum ETF",        "category": "Healthcare"},
    {"ticker": "PXI",  "name": "Invesco DWA Energy Momentum ETF",            "category": "Energy"},
    {"ticker": "PEZ",  "name": "Invesco DWA Consumer Cyclicals Momentum ETF","category": "Consumer Discret"},
    {"ticker": "PSL",  "name": "Invesco DWA Consumer Staples Momentum ETF",  "category": "Consumer Staples"},
    {"ticker": "PRN",  "name": "Invesco DWA Industrials Momentum ETF",       "category": "Industrials"},
    {"ticker": "PFI",  "name": "Invesco DWA Financial Momentum ETF",         "category": "Financials"},
    {"ticker": "PUI",  "name": "Invesco DWA Utilities Momentum ETF",         "category": "Utilities"},
    {"ticker": "AWAY", "name": "ETFMG Travel Tech ETF",                      "category": "Thematic"},
    {"ticker": "EATV", "name": "VegTech Plant-based Innovation & Climate ETF","category": "Thematic"},
    {"ticker": "BMED", "name": "BlackRock Future Health ETF",                "category": "Healthcare"},

    # ── ADDITIONAL GLOBAL EQUITY ─────────────────────────────────────────────
    {"ticker": "ACWX", "name": "iShares MSCI ACWI ex US ETF",               "category": "Global"},
    {"ticker": "CWI",  "name": "SPDR MSCI ACWI ex-US ETF",                  "category": "Global"},
    {"ticker": "URTH", "name": "iShares MSCI World ETF",                     "category": "Global"},
    {"ticker": "GSIE", "name": "Goldman Sachs ActiveBeta International Equity ETF","category": "Intl Developed"},
    {"ticker": "XSEM", "name": "iShares MSCI EAFE Small-Cap ETF",           "category": "Intl Developed"},
    {"ticker": "GWX",  "name": "SPDR S&P International Small Cap ETF",       "category": "Intl Developed"},
    {"ticker": "SCZ",  "name": "iShares MSCI EAFE Small-Cap ETF",            "category": "Intl Developed"},
    {"ticker": "SCHC", "name": "Schwab International Small-Cap Equity ETF",  "category": "Intl Developed"},
    {"ticker": "VSS",  "name": "Vanguard FTSE All-World ex-US Small-Cap ETF","category": "Intl Developed"},
    {"ticker": "DLS",  "name": "WisdomTree International SmallCap Dividend ETF","category": "Intl Developed"},
    {"ticker": "DGS",  "name": "WisdomTree Emerging Markets SmallCap Dividend ETF","category": "Emerging Markets"},
    {"ticker": "EWX",  "name": "SPDR S&P Emerging Markets Small Cap ETF",   "category": "Emerging Markets"},
]

def get_all_tickers():
    seen = set()
    unique = []
    for f in FUNDS:
        if f["ticker"] not in seen:
            seen.add(f["ticker"])
            unique.append(f)
    return unique

def get_ticker_info():
    return {f["ticker"]: {"name": f["name"], "category": f["category"]} for f in get_all_tickers()}
